name: Web Dashboard CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]  # Use self-hosted Windows runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # List published files for debugging
      - name: List published files
        run: dir ./publish  # Changed to dir for Windows

      # Upload published files as artifact
      - name: Upload published files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-dashboard-artifact
          path: ./publish

  deploy:
    runs-on: [self-hosted, windows]  # Use self-hosted Windows runner

    needs: build  # Ensure that the build job has completed before deployment

    steps:
      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: web-dashboard-artifact
          path: ./artifact

      # Clean existing files and apply new files on local runner
      - name: Clean and Apply Changes on Local Runner
        run: |
          # Define the target directory inside the 'wwwroot' folder
          $targetDir = 'C:\inetpub\wwwroot\Web dashboard'
          
          # Stop IIS worker processes to free any locked files
          Stop-Process -Name w3wp -Force -ErrorAction SilentlyContinue;
          
          # Remove the existing 'Web dashboard' folder and its contents
          Remove-Item -Path "$targetDir" -Recurse -Force -ErrorAction SilentlyContinue;
          
          # Rename the downloaded artifact folder to 'Web dashboard'
          Rename-Item -Path './artifact/web-dashboard-artifact/publish' -NewName 'Web dashboard'
          
          # Move the new 'Web dashboard' folder to the target directory
          Move-Item -Path './artifact/web-dashboard-artifact/Web dashboard' -Destination $targetDir -Recurse -Force;
          
          # Restart IIS to apply the changes
          iisreset

      # Restart IIS to apply the changes
      - name: Restart IIS Service
        run: |
          # Restart IIS on the local machine
          iisreset
