name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # Deploy to Windows Server
      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 44.222.253.64 
          username: Administrator
          password: 5Rc-e2$AUvheMYsx.T%5TX)=Rnp=Nr5p
          port: 22  # Default SSH port
          script: |
            # Remove existing files in the publish folder (to replace them)
            Remove-Item -Path "C:/inetpub/wwwroot/publish" -Recurse -Force
            # Copy the new files from the local publish directory
            Copy-Item -Path "C:/publish/*" -Destination "C:/inetpub/wwwroot/publish/" -Recurse -Force

      # Restart IIS to apply the changes (using SSH)
      - name: Restart IIS Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 44.222.253.64
          username: Administrator
          password: 5Rc-e2$AUvheMYsx.T%5TX)=Rnp=Nr5p
          port: 22
          script: |
            # Restart IIS service
            iisreset
