name: Web Dashboard CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]  # Use self-hosted Windows runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # List published files for debugging
      - name: List published files
        run: dir ./publish  # Changed to dir for Windows

      # Clean existing files and apply new files on local runner
      - name: Clean and Apply Changes on Local Runner
        run: |
          # Define the target directory on the local machine (self-hosted runner)
          $targetDir = 'C:\inetpub\wwwroot\Web dashboard'
          
          # Stop IIS worker processes to free any locked files
          Stop-Process -Name w3wp -Force -ErrorAction SilentlyContinue;
          
          # Remove all files and subdirectories inside the 'publish' folder on the local runner
          Remove-Item -Path "$targetDir\*" -Recurse -Force -ErrorAction SilentlyContinue;
          
          # Copy the newly published files to the target directory
          Copy-Item -Path './publish/*' -Destination $targetDir -Recurse -Force;
          
          # Restart IIS to apply the changes
          iisreset

      # Restart IIS to apply the changes
      - name: Restart IIS Service
        run: |
          # Restart IIS on the local machine
          iisreset
