name: Web Dashboard CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]  # Use self-hosted Windows runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # List the contents of the publish directory for debugging
      - name: List published files
        run: dir ./publish  # This will show the files in the 'publish' directory

      # Move the published files to 'wwwroot' folder
      - name: Move published files to wwwroot
        run: |
          # Define the target directory inside the 'wwwroot' folder
          $targetDir = 'C:\inetpub\wwwroot\Web dashboard'
          
          # Stop IIS worker processes to free any locked files
          Stop-Process -Name w3wp -Force -ErrorAction SilentlyContinue;
          
          # Remove the existing 'Web dashboard' folder and its contents
          Remove-Item -Path "$targetDir" -Recurse -Force -ErrorAction SilentlyContinue;
          
          # Copy the files from the 'publish' directory to the 'wwwroot' folder
          Copy-Item -Path './publish/*' -Destination $targetDir -Recurse -Force;
          
          # Restart IIS to apply the changes
          iisreset

      # Restart IIS to apply the changes
      - name: Restart IIS Service
        run: |
          # Restart IIS on the local machine
          iisreset
