name: Web Dashboard CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # Transfer published files to Windows Server
      - name: Transfer Published Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 20.0.3.56
          username: Administrator
          password: Atrity@123
          source: ./publish/*
          target: C:/inetpub/wwwroot/

      # Clean existing files and apply new files
      - name: Clean and Apply Changes
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 20.0.3.56
          username: Administrator
          password: Atrity@123
          port: 22
          script: |
            powershell.exe -Command "
              # Stop IIS worker processes to free any locked files
              Stop-Process -Name w3wp -Force -ErrorAction SilentlyContinue;

              # Remove all files and subdirectories inside the 'publish' folder
              Get-ChildItem -Path 'C:/inetpub/wwwroot/Web dashboard' -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue;

              # Remove the 'publish' directory itself if empty
              Remove-Item -Path 'C:/inetpub/wwwroot/Web dashboard' -Recurse -Force -ErrorAction SilentlyContinue;

              # Move the newly published files to the wwwroot folder
              Move-Item -Path 'C:/inetpub/wwwroot/Web dashboard/*' -Destination 'C:/inetpub/wwwroot/' -Recurse -Force;
            "

      # Restart IIS to apply the changes
      - name: Restart IIS Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 20.0.3.56
          username: Administrator
          password: Atrity@123
          port: 22
          script: |
            :: Restart IIS to apply changes
            iisreset
